# Generated by Django 3.2.16 on 2023-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_number', max_length=100, null=True)),
                ('status', models.IntegerField(db_column='Status')),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('modified_user', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployePasswords',
            fields=[
                ('emp_password_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('modified_user', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employe_passwords',
                'managed': False,
            },
        ),
    ]
